---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-kubeflow
  version: "1.18"
  region: ap-northeast-1
managedNodeGroups:
- name: eks-cpu
  desiredCapacity: 2
  minSize: 0
  maxSize: 6
  instanceType: m5.large
  availabilityZones: ["ap-northeast-1a"]
  volumeSize: 50
  tags: {"k8s.io/cluster-autoscaler/enabled": "true", "k8s.io/cluster-autoscaler/kf-cluster": "owned"}
- name: eks-gpu
  instanceType: p3.2xlarge
  availabilityZones: ["ap-northeast-1c"]
  desiredCapacity: 0
  minSize: 0
  maxSize: 2
  volumeSize: 50
  tags:
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/kf-cluster: "owned"
    k8s.io/cluster-autoscaler/node-template/taint/dedicated: "nvidia.com/gpu=true"
    k8s.io/cluster-autoscaler/node-template/label/nvidia.com/gpu: "true"
  labels:
    nvidia.com/gpu: "true"
    k8s.amazonaws.com/accelerator: nvidia-tesla
  taints: [{"key": "nvidia.com/gpu", "value": "true", "effect":"NoSchedule"}]
